import { test, expect } from '@playwright/test';
import { readFile, mkdir, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { execFileSync, spawnSync } from 'node:child_process';
import { unzipSync, strFromU8 } from 'fflate';
import { sampleProject } from '../src/core/sample';
test('validates, fixes, manages fixtures and runs exported Node tests',async ({page}) => {
  const consoleErrors:string[]=[]; page.on('pageerror',e=>consoleErrors.push(e.message));
  await page.goto('./');
  await expect(page.getByText('2/2',{exact:true})).toBeVisible();
  await page.getByRole('button',{name:/Type drift/}).click();
  await expect(page.locator('.pointer').filter({hasText:'/items/0/quantity'})).toBeVisible();
  await page.getByLabel('JSON response',{exact:true}).fill('{"id":1042,"status":"paid","items":[{"sku":"BK-001","quantity":2}]}');
  await expect(page.getByText('Expectation mismatch',{exact:true})).toBeVisible();
  await page.getByLabel('Expected outcome').selectOption('valid');
  await expect(page.getByText('2/2',{exact:true})).toBeVisible();
  await page.getByRole('button',{name:'Duplicate',exact:true}).click();
  await page.getByLabel('Fixture name').fill('Regression');
  await expect(page.getByRole('button',{name:/Regression/})).toBeVisible();
  await page.getByRole('button',{name:'Delete',exact:true}).click();
  await page.getByRole('button',{name:'Confirm',exact:true}).click();
  await expect(page.getByText('2/2',{exact:true})).toBeVisible();
  const [download] = await Promise.all([page.waitForEvent('download'),page.getByRole('button',{name:'Export tests',exact:true}).click()]);
  const path=await download.path(); const files=unzipSync(await readFile(path!));
  const output=join(tmpdir(),'shapecheck-export-'+Date.now()); await mkdir(output);
  for(const [name,data] of Object.entries(files)) await writeFile(join(output,name),data);
  const result=execFileSync(process.execPath,['--test','test.mjs'],{cwd:output,encoding:'utf8'});
  expect(result).toContain('fail 0');
  // Deliberate regression must fail, proving exported tests are executable assertions.
  const project=JSON.parse(strFromU8(files['project.json'])); project.fixtures[0].payload='{}';
  await writeFile(join(output,'project.json'),JSON.stringify(project));
  expect(()=>execFileSync(process.execPath,['--test','test.mjs'],{cwd:output,stdio:'pipe'})).toThrow();
  await writeFile(join(output,'project.json'),'{"token":"SECRET_SENTINEL",');
  const corrupt=spawnSync(process.execPath,['--test','test.mjs'],{cwd:output,encoding:'utf8'});
  expect(corrupt.status).not.toBe(0);expect(corrupt.stdout+corrupt.stderr).not.toContain('SECRET_SENTINEL');
  expect(consoleErrors).toEqual([]);
});
test('large edits and duplicate respect byte boundaries without losing the workspace',async ({page}) => {
  await page.goto('./');const original=await page.getByLabel('JSON Schema',{exact:true}).inputValue();
  await page.getByLabel('JSON Schema',{exact:true}).fill(' '.repeat(65537));
  await expect(page.getByLabel('JSON Schema',{exact:true})).toHaveValue(original);
  const p=sampleProject();p.schema='true';p.fixtures=Array.from({length:4},(_,i)=>({id:'large'+i,name:'Large '+i,expected:'valid' as const,payload:JSON.stringify('a'.repeat(250000))}));
  await page.locator('input[type=file]').setInputFiles({name:'project.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(p))});
  await page.getByRole('button',{name:'Confirm',exact:true}).click();
  await page.getByRole('button',{name:'Duplicate',exact:true}).click();
  await expect(page.locator('.fixture-item')).toHaveCount(4);
  await expect(page.getByText('Size limit reached. The edit was not applied; your workspace is unchanged.')).toBeVisible();
});
test('keyboard check and exact error navigation work for repeated array keys',async ({page}) => {
  await page.goto('./');await page.getByRole('button',{name:/Type drift/}).click();
  await page.getByLabel('JSON response',{exact:true}).fill('{"id":1042,"status":"paid","items":[{"sku":"A","quantity":1},{"sku":"B","quantity":0}]}');
  await page.keyboard.press('Control+Enter');
  const card=page.locator('.issue-card').filter({hasText:'/items/1/quantity'});
  await card.getByRole('button',{name:'Jump to field'}).click();
  const selection=await page.getByLabel('JSON response',{exact:true}).evaluate((node:HTMLTextAreaElement)=>({start:node.selectionStart,text:node.value}));
  expect(selection.start).toBe(selection.text.lastIndexOf('"quantity"'));
});
test('syntax, safety, unknown keywords and corrupt imports cannot produce pass',async ({page}) => {
  await page.goto('./'); await expect(page.getByText('2/2',{exact:true})).toBeVisible();
  await page.getByLabel('JSON response',{exact:true}).fill('{"token":"SECRET_SENTINEL",');
  await expect(page.locator('.result-banner').getByText('JSON syntax error',{exact:true})).toBeVisible();
  await expect(page.locator('.result-content')).not.toContainText('SECRET_SENTINEL');
  await page.getByLabel('JSON Schema',{exact:true}).fill('{"$ref":"https://example.com/schema"}');
  await expect(page.getByText('Safety limit',{exact:true})).toBeVisible();
  await page.getByLabel('JSON Schema',{exact:true}).fill('{"unknownKeyword":true}');
  await expect(page.getByText('Safety limit',{exact:true})).toBeVisible();
  await page.locator('input[type=file]').setInputFiles({name:'corrupt.json',mimeType:'application/json',buffer:Buffer.from('{"version":1,"__proto__":{}}')});
  await expect(page.getByText('Import rejected. Your current workspace is unchanged.')).toBeVisible();
  await expect(page.getByLabel('JSON Schema',{exact:true})).toHaveValue('{"unknownKeyword":true}');
});
test('storage is opt-in and clear preserves unrelated data',async ({page}) => {
  await page.goto('./');
  await page.evaluate(()=>localStorage.setItem('unrelated','keep'));
  await expect(page.getByRole('checkbox',{name:'Remember on this device'})).not.toBeChecked();
  await page.getByLabel('Project name').fill('Saved project');
  await page.getByRole('checkbox',{name:'Remember on this device'}).check();
  await page.reload(); await expect(page.getByLabel('Project name')).toHaveValue('Saved project');
  await page.getByRole('button',{name:'Clear workspace',exact:true}).click();
  await page.getByRole('button',{name:'Keep workspace',exact:true}).click();
  await expect(page.getByLabel('Project name')).toHaveValue('Saved project');
  await page.getByRole('button',{name:'Clear workspace',exact:true}).click();
  await page.getByRole('button',{name:'Confirm',exact:true}).click();
  expect(await page.evaluate(()=>localStorage.getItem('unrelated'))).toBe('keep');
  expect(await page.evaluate(()=>localStorage.getItem('shapecheck.workspace.v1'))).toBeNull();
});
test('imports, escapes hostile strings and localizes all controls',async ({page}) => {
  await page.goto('./'); const p=sampleProject(); p.name='<img src=x onerror=alert(1)>'; p.fixtures[0].name='<script>alert(1)</script>';
  await page.locator('input[type=file]').setInputFiles({name:'project.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(p))});
  await page.getByRole('button',{name:'Confirm',exact:true}).click();
  await expect(page.getByLabel('Project name')).toHaveValue(p.name); await expect(page.locator('img')).toHaveCount(0);
  await page.getByLabel('Language').selectOption('ru'); await expect(page.getByRole('button',{name:'Проверить все',exact:true})).toBeVisible();
  await page.getByRole('button',{name:'Ограничения и помощь',exact:true}).click();
  await expect(page.getByRole('dialog')).toContainText('Без сервера и телеметрии');
  await page.keyboard.press('Escape'); await expect(page.getByRole('dialog')).not.toBeVisible();
});
test('cancel and rerun terminate a stalled worker',async ({page}) => {
  let stalled=false;
  await page.route('**/validation.worker-*.js',async route=>{
    await route.fulfill({contentType:'text/javascript',body:'self.onmessage=()=>{};self.postMessage({type:"ready"});'});
    stalled=true;
  });
  await page.goto('./'); await expect.poll(()=>stalled).toBe(true);
  await page.getByRole('button',{name:'Cancel',exact:true}).click();
  await expect(page.getByText('Cancelled',{exact:true}).first()).toBeVisible();
  await page.unroute('**/validation.worker-*.js');
  await page.getByRole('button',{name:'Check all',exact:true}).click();
  await expect(page.getByText('2/2',{exact:true})).toBeVisible({timeout:15000});
});
test('cold worker downloads do not consume the validation deadline',async({page})=>{
  await page.route('**/validation.worker-*.js',async route=>{await new Promise(r=>setTimeout(r,2500));await route.continue();});
  await page.goto('./');await expect(page.getByText('2/2',{exact:true})).toBeVisible({timeout:10000});
});
